apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<<account_id>>:role/DCADevEKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<<account_id>>:role/OktaSSOAdmin
      username: OktaSSOAdmin
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<<account_id>>:role/Admin
      username: Admin
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<<account_id>>:role/dca-github-actions-role
      username: Admin
